# Task 1

Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
import numpy as np

In [204]:

def vanderMonde_matrix(vector, n=None, increasing=False):
    
    if not increasing:
        if n is None:
            n=len(vector)
            matrix = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
        else:
            matrix = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
            
    elif increasing:
        if n is None:
            n=len(vector)
            matrix = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
        else:
            matrix = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
            
    
    return matrix


In [205]:
x = np.array([1, 2, 3,5])

##### N' is not set And Increasing is False. So Number of Column of Output Matrix will be same length as vector x

In [224]:
vanderMonde_matrix(x,increasing=False)


array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

##### 'N' is not set And Increasing is True. So Number of Column of Output Matrix will be same length as vector x"

In [208]:

vanderMonde_matrix(x,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

##### 'N' is set And Increasing is "False". So Number of Column of Output Matrix will be same length as vector x

In [211]:
N=3
vanderMonde_matrix(x,N,increasing=False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

###### N' is set And Increasing is "True". So Number of Column of Output Matrix will be same length as vector x

In [212]:
N=3
vanderMonde_matrix(x,N,increasing=True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

# Task 2

Write a function to find moving average in an array over a window: 
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [216]:
def moving_average(a,n) :
    ret = np.cumsum(a)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_average(a,3)


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])